Update crop text tooltip
Total-RP/Total-RP-3 pull request #1109
Opened 2024-08-01 11:22 UTC by Raenore

We have more (and updated) croppings since 3.0.0, but our settings tooltip didn't reflect that.

Where known translations exist for these options (Name, Pronouns, Volice ref, etc.) is where I applied these.

Translations that didn't exist for certain words (mostly guild name/rank) have been kept in English and can be translated later.

2024-08-01 11:24 UTC, Meorawr requested changes
If we're doing this I'm tempted to make a few suggestions;

1. Those `FIELDS_TO_CROP` tables in RegisterTooltip.lua are (essentially) duplicated three times. Make the one from `writeTooltipForCharacter` global (call it `TRP3_TooltipCroppingConstants`) and adjust all of the `FIELDS_TO_CROP` lookups to consult that table.
2. Convert these localization strings to just have format specifiers like %d, and then format in the crop sizes from that global table. That way we won't forget to update them in the future, and don't need to deal with importing localization into CF.

2024-08-01 11:26 UTC, Meorawr commented
As an alternative I'd be totally down for just also _removing_ the crop lengths from the settings tooltip entirely.

2024-08-01 12:01 UTC, Raenore commented
Did the global and removed the info from the tooltip setting as it'd just bloat if we do add more cropping.

2024-08-01 12:02 UTC, Meorawr requested changes

2024-08-01 12:02 UTC, Meorawr commented on totalRP3/Modules/Register/Main/RegisterTooltip.lua
> +}
```suggestion
};
```

WHERE'S THE LAMB SAUCE

2024-08-01 12:13 UTC, Meorawr approved these changes

2024-08-12 17:28 UTC, Solanya approved these changes

2024-08-12 17:28 UTC, merged