include missing modifiers in dice roll output strings
Total-RP/Total-RP-3 pull request #449
Opened 2020-10-20 23:46 UTC by Connor-Macleod

the string that prints the result of dice rolls currently don’t include the modifier, wich causes confusion for users. this adresses that issue.

2020-10-21 06:26 UTC, Ellypse commented
As this introduces a new string replacement token in a locale string, it might cause issues with other languages in which this key was already localized a long time ago.

We’ll need to either look at all the localizations on CurseForge and modify them accordingly, or use a new key for this string and require it to be translated again.

2020-10-21 07:41 UTC, Solanya requested changes
A few comments :
- The loc string you modified is the one for your own roll (DICE_ROLL) but you didn't modify the part that shows that string (Line 134)
- Vice versa, the part you modified is the one for the person receiving your roll (DICE_ROLL_T) but that loc string hasn't been modified.
- I think there's a bit more formatting to do on those strings. If the modifier value is positive, we need a + in front of it. If the modifier value is 0, the modifier string should be empty (1d6+0, ehhh).

2020-10-21 09:28 UTC, Meorawr commented on totalRP3/core/impl/slash.lua
> +		local modifierString = (modifierValue ~= 0) and ((modifierValue > 0 and '+')..(modifierValue)) or ''; -- we add a + to positive modifiers and don't render a 0 value
The following would be shorter and equivalent:
```lua
local modifierString = (modifierValue == 0) and "" or format("%+d", modifierValue);
```

![image](https://user-images.githubusercontent.com/287102/96701096-1f819c80-1388-11eb-97b3-8091000ee993.png)

2020-10-21 09:31 UTC, Solanya commented on totalRP3/core/impl/slash.lua
> +		local modifierString = (modifierValue ~= 0) and ((modifierValue > 0 and '+')..(modifierValue)) or ''; -- we add a + to positive modifiers and don't render a 0 value
```suggestion
		local modifierString = (modifierValue == 0) and "" or format("%+d", modifierValue); -- we add a + to positive modifiers and don't render a 0 value
```

2020-10-21 09:32 UTC, Solanya commented on totalRP3/core/impl/slash.lua
> +					local modifierString = (arg.m ~= 0) and ((arg.m > 0 and '+')..(arg.m)) or ''; -- we add a + to positive modifiers and don't render a 0 value
```suggestion
					local modifierString = (arg.m == 0) and "" or format("%+d", arg.m); -- we add a + to positive modifiers and don't render a 0 value
```

2020-10-21 10:15 UTC, Meorawr approved these changes

2020-10-21 10:15 UTC, Meorawr commented on totalRP3/tools/Locale.lua
> +	DICE_ROLL = "%s Rolled |cffff9900%sx d%s|r|cffCC6600%s|r and got |cff00ff00%s|r.",
```suggestion
	DICE_ROLL = "%s Rolled |cffff9900%sx d%s|r|cffcc6600%s|r and got |cff00ff00%s|r.",
```

2020-10-21 10:15 UTC, Meorawr commented on totalRP3/tools/Locale.lua
> +	DICE_ROLL_T = "%s %s rolled |cffff9900%sx d%s|r|cffCC6600%s|r and got |cff00ff00%s|r.",
```suggestion
	DICE_ROLL_T = "%s %s rolled |cffff9900%sx d%s|r|cffcc6600%s|r and got |cff00ff00%s|r.",
```

2020-10-23 12:09 UTC, Solanya approved these changes

2020-10-23 12:10 UTC, Meorawr approved these changes

2020-11-16 14:52 UTC, merged