Allow opening profiles from player map scan pins
Total-RP/Total-RP-3 pull request #660
Opened 2022-11-05 15:48 UTC by Meorawr

This adds a *left* click popup that offers an "Open profile" option when clicking on pins for scanned players on the map.

If players are grouped, the entries will be coaleseced into the displayed dropdown which will show (up-to) 25 "open profile" options, each showing the players' name.

2022-11-05 16:12 UTC, Solanya approved these changes

2022-11-05 16:17 UTC, Solanya requested changes
I probably want to add "Right-click: ..." on the tooltip before merging

2022-11-12 19:45 UTC, Meorawr commented
I have made the changes for you, old man.

2022-11-13 15:38 UTC, Solanya approved these changes

2022-11-13 15:38 UTC, merged