Additional toolbar visibility options
Total-RP/Total-RP-3 pull request #699
Opened 2023-02-21 09:59 UTC by Ghostamoose

Originally suggested by `Tonberry#4901` in the TRP Discord.

Currently there's only two visibility options for the TRP toolbar, it's either shown on login or it's not. Here I'm adding the option to show the toolbar only when in-character, with the toolbar disappearing when the player goes out-of-character. Additionally, there's also options to show on login, and hide by default.

Users can still freely toggle the toolbar using the minimap icon or the `/trp3 switch toolbar` slash command.

![image](https://user-images.githubusercontent.com/10636803/220311551-be0997a7-865c-44cd-8d24-36e96857c353.png)

**To do:**
- [ ] - Finalize strings
- [ ] - Finalize visibility choices

2023-02-21 10:05 UTC, Ghostamoose commented on totalRP3/Locales/Locale.lua
> +	CO_TOOLBAR_VISIBILITY_3 = "Hide toolbar",
wtb strings

2023-02-21 10:06 UTC, Meorawr requested changes
General comment - where's the ~~lamb sauce~~ semicolons?

2023-02-21 10:06 UTC, Meorawr commented on totalRP3/Locales/Locale.lua
> +	CO_TOOLBAR_VISIBILITY_3 = "Hide toolbar",
```lua
CO_TOOLBAR_VISIBILITY = "Toolbar Visibility"
CO_TOOLBAR_VISIBILITY_HELP = "Configures the conditions under which the toolbar will be shown."
CO_TOOLBAR_VISIBILITY_1 = "Always show"
CO_TOOLBAR_VISIBILITY_1 = "Only show in character"
CO_TOOLBAR_VISIBILITY_1 = "Always hidden"
```

2023-02-21 10:06 UTC, Meorawr commented on totalRP3/Modules/Toolbar/Toolbar.lua
> +				{loc.CO_TOOLBAR_VISIBILITY_3, 3}
Make a local enum in this file and swap to using named constants.

```lua
local ToolbarVisibilityOption = {
    AlwaysShow = 1,
    OnlyShowInCharacter = 2,
    AlwaysHidden = 3,
};
```

2023-02-21 10:06 UTC, Meorawr commented on totalRP3/Modules/Toolbar/Toolbar.lua
> +			if player:IsInCharacter() then toolbar:Show() else toolbar:Hide() end
Why is this all on one line?

2023-02-21 10:37 UTC, Ghostamoose commented on totalRP3/Locales/Locale.lua
> +	CO_TOOLBAR_VISIBILITY_HELP = "MEO_PHONE_HOME", --FIXME: don't forget to fix this later
elp string needs elp

2023-02-21 10:40 UTC, Meorawr requested changes
I'd also prefer the visibility logic be moved to a function.

```lua
local function ShouldShowToolbar()
    local preferredVisibility = TRP3_API.configuration.getValue(CONFIG_TOOLBAR_VISIBILITY);

    if preferredVisibility == ToolbarVisibilityOption.AlwaysHidden then
        return false;
    elseif preferredVisibility == ToolbarVisibilityOption.OnlyShowInCharacter then
        local player = AddOn_TotalRP3.Player.GetCurrentUser();
        return player:IsInCharacter();
    else
        return true;
    end
end
```

Then all those Show/Hide calls can just be shortened to:

````lua
toolbar:SetShown(ShouldShowToolbar());
````

2023-02-21 14:19 UTC, Meorawr requested changes
I need to think some more on the actual logic changes.

2023-02-21 14:19 UTC, Meorawr commented on totalRP3/Locales/Locale.lua
> +	CO_TOOLBAR_VISIBILITY_HELP = "help me",
```lua
CO_TOOLBAR_VISIBILITY_HELP = "Configures the conditions under which the toolbar should be shown.|n|nThe visibility of the toolbar can be forcefully toggled by running the |cff00ff00/trp switch toolbar|r slash command or by right-clicking the minimap button, which will persist until either logout or a UI reload."
```

2023-02-21 23:50 UTC, Meorawr submitted a review, later dismissed
Approving in terms of functional requirements being met and basic testing of the feature in all states proving rather fruitful, though Sol should give it a once-over to see if anything looks amiss.

2023-02-22 18:30 UTC, Solanya commented on totalRP3/Modules/Toolbar/Toolbar.lua
> +	self.manualVisibility = nil;
I'm guessing this should have been forcedVisibility?

2023-02-22 21:01 UTC, Solanya approved these changes

2023-02-23 09:22 UTC, merged