Consistency pass of settings pages
Total-RP/Total-RP-3 pull request #982
Opened 2024-07-10 01:08 UTC by Solanya

- Repeating "settings" on the tab names made them crop when the section title already indicates that these are "Settings". Keys in all languages we could somewhat interpret where changed to remove this.
- As an added thing, "Frames settings" was split into "Toolbar" and "Target Frame".

Two things worth discussing:
- There is the small matter of the map button settings. I moved it in General for now as this was the simplest solution. It's possible it should be in the Directory category instead next to the Location settings, but that requires a lot more changes, so I'd like to double-check if we have an alternative idea first.
- Register was renamed to Directory, which means the non-special categories are not in alphabetical order anymore. Then again, other languages were also not in alphabetical order. Do we still want to change it?

![image](https://github.com/Total-RP/Total-RP-3/assets/17127080/1d56b266-5f90-4c60-b9c3-831333fb3afc)

2024-07-13 13:09 UTC, Meorawr approved these changes
One comment that "Chat frames" is used as the string in enUS but a bunch of others are still "Chat".

2024-07-14 14:33 UTC, Solanya commented
Put the name singular and reused the global string from Blizzard. Should be good now.

2024-07-14 15:17 UTC, Meorawr requested changes

2024-07-14 15:17 UTC, Meorawr commented on totalRP3/Locales/frFR.lua
> +	["CO_CHAT"] = "	Fenêtre de discussion",
Why the leading space bro

2024-07-14 15:18 UTC, Meorawr approved these changes
I approve of this ramen.

2024-07-14 15:19 UTC, merged